---
title: "NetworkAnalysis"
author: "Zijian Wang"
date: "1/28/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#https://github.com/stefpeschel/NetCoMi
setwd("/Users/zijianleowang/Desktop/GitHub/NetworkAnalysis/scripts")
library(NetCoMi)
```

```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 1080,
                      echo = FALSE,
                      cache = TRUE)
```

```{r}

get.dat <- function(path){
# load data n x d (samples x OTUs)
dat <- read.table(path,sep='\t',header = TRUE,row.names = 1)
dat[is.na(dat)] <- 0
return (dat)
}

# calculate network
get.network <- function(dat,pathout,method){
  if (method=="spearman"){
    measure="spearman"
    measurePar=list(na.rm=TRUE)
  } else if (method=="spring"){
    measure = "spring" #associations between taxa
    measurePar = list(nlambda=10,
                      rep.num=10)
  } else if (method=="sparcc"){
    measure = "sparcc" #associations between taxa
    measurePar = list(iter=20,inner_iter=15)
  } else if (method=="pearson"){
    measure = "pearson" #associations between taxa
    measurePar = list(na.rm=TRUE)
  }
net_spring <- netConstruct(dat,
                           filtTax = "highestFreq",
                           filtTaxPar = list(highestFreq = 50),
                           filtSamp = "totalReads",
                           filtSampPar = list(totalReads = 0.01),# my data is abundance
                           measure = measure,#associations between taxa 
                           measurePar = measurePar,
                           normMethod = "none", 
                           zeroMethod = "none",
                           sparsMethod = "none", 
                           dissFunc = "signed",
                           verbose = 2,
                           seed = 123456)

# analyze it
props_spring <- netAnalyze(net_spring, 
                           centrLCC = TRUE,
                           gcmHeat = FALSE, # not to plot automatically
                           clustMethod = "cluster_fast_greedy",
                           hubPar = "eigenvector",
                           weightDeg = FALSE, normDeg = FALSE)

# plot manually
# plot the matrix
png(paste(pathout,'/GCM.cluster.',method,'.png',sep=""),width=700,height=600)
plotHeat(mat = props_spring$graphletLCC$gcm1,
         pmat = props_spring$graphletLCC$pAdjust1,
         type = "mixed",
         title = "GCM", 
         #textCex = 0.5,
         colorLim = c(-1, 1),
         mar = c(2, 0, 2, 0))

# Add rectangles highlighting the four types of orbits
graphics::rect(xleft   = c( 0.5,  1.5, 4.5,  7.5),
               ybottom = c(11.5,  7.5, 4.5,  0.5),
               xright  = c( 1.5,  4.5, 7.5, 11.5),
               ytop    = c(10.5, 10.5, 7.5,  4.5),
               lwd = 2, xpd = NA)

text(6, -0.2, xpd = NA, 
     "Significance codes:  ***: 0.001;  **: 0.01;  *: 0.05")

dev.off()

# summary 
outputfile <- paste(pathout,'/network.summary.',method,'.txt',sep="")
# sink()
# print(summary(props_spring, numbNodes = 5L))
# sink()  # returns output to the console
dput(summary(props_spring, numbNodes = 5L),file=outputfile,control="all")

# viz the network
png(paste(pathout,'/network_',method,'.png',sep=""),width=1920,height=1920)

p <- plot(props_spring, 
          nodeColor = "cluster", 
          nodeSize = "eigenvector",
          title1 = paste("Network on OTU level with",method,"  associations"), 
          showTitle = TRUE,
          cexNodes = 6,
          cexTitle = 0.8)

legend(0.5, 1.1, cex = 0.8, title = "estimated association:",
       legend = c("+","-"), lty = 1, lwd = 3, col = c("#009900","red"), 
       bty = "n", horiz = TRUE)
dev.off()
}
main <- function(pathin,pathout,method,split=FALSE){
  
  dat <- get.dat(pathin)
  if (class(split)=="list"){
    for (paths in pathout){
    if (!dir.exists(paths)){
  dir.create(paths,recursive = TRUE)}} # create multiple pathout
    # split the data given split as a vector
    for (i in seq_along(split)){
      get.network(dat[split[i][[1]],],pathout[i],method)
    }
  }
  else if (split==FALSE){
    if (!dir.exists(pathout)){
  dir.create(pathout,recursive = TRUE)} # create one pathout
  get.network(dat,pathout,method)}
  
  }
```

```{r}
# # Peisheng Data
# pathin = "../data/Peisheng/abundance/genus.tsv"
# pathout = "../output/Peisheng/Soil01"
# main(pathin,pathout,"spearman")

# Zhou SOil Old Data
# pathin = "../../EasyMicrobiome/data/ZhouSoil16S/Old/abundance/genus.tsv"
# pathout = "../output/ZhouSoil/Old"
# main(pathin,pathout,"spearman")
# main(pathin,pathout,"sparcc")
# main(pathin,pathout,"pearson")

# Zhou SOil Old Data by separating sorted and unsorted
# pathin = "../../EasyMicrobiome/data/ZhouSoil16S/Old/abundance/genus.tsv"
# pathout = list(p1="../output/ZhouSoil/Old/unsorted",p2="../output/ZhouSoil/Old/sorted")
# main(pathin,pathout,"spearman",seq(1,23,2))
# main(pathin,pathout,"sparcc",seq(1,23,2))
# main(pathin,pathout,"pearson",seq(1,23,2))

# Zhou SOil New Data
# pathin = "../../EasyMicrobiome/data/ZhouSoil16S/New/abundance/genus.tsv"
# pathout = "../output/ZhouSoil/New"
# main(pathin,pathout,"spearman")
# main(pathin,pathout,"sparcc")
# main(pathin,pathout,"pearson")

# Zhou Soil New Data by separating sorted and unsorted
# pathin = "../../EasyMicrobiome/data/ZhouSoil16S/New/abundance/genus.tsv"
# pathout = list(p1="../output/ZhouSoil/New/unsorted",p2="../output/ZhouSoil/New/sorted")
# main(pathin,pathout,"spearman",seq(1,48,2))
# main(pathin,pathout,"sparcc",seq(1,48,2))
# main(pathin,pathout,"pearson",seq(1,48,2))

# CROPPS SUmmer 2022 Winter Wheat
pathin = "../../EasyMicrobiome/data/CROPPS2022Summer16S/abundance/genus.tsv"
pathout = c("../output/CROPPS/2022SummerWheat/Normal",
               "../output/CROPPS/2022SummerWheat/Wet",
               "../output/CROPPS/2022SummerWheat/Tower")
split = list(
  c(seq(1,4),seq(13,16),seq(25,28),seq(37,40)),
  c(seq(1,4),seq(13,16),seq(25,28),seq(37,40))[1:15]+4,
  c(seq(1,4),seq(13,16),seq(25,28))+8
)
main(pathin,pathout,"spearman",split)
main(pathin,pathout,"sparcc",split)
main(pathin,pathout,"pearson",split)
```

```{r}
# Dongqi HRSD Data
pathin = "../data/Dongqi/HRSD/abundance/genus.tsv"
pathout = "../output/Dongqi/HRSD"
main(pathin,pathout,"spearman")
main(pathin,pathout,"sparcc")
main(pathin,pathout,"pearson")
```


```{r network-plot, dev = c("png")}

```

